# Generated by Django 2.2.16 on 2021-08-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='planned_finish',
            new_name='plan_complet_date',
        ),
    ]
