# Generated by Django 2.2.16 on 2021-08-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210826_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'новая'), ('planned', 'запланированная'), ('in_progress', 'в работе'), ('completed', 'завершенная')], max_length=11, null=True)),
                ('plan_complet_date', models.DateField(blank=True, null=True)),
                ('date_change', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
            options={
                'ordering': ['-date_change'],
            },
        ),
    ]
