# Generated by Django 2.2.16 on 2021-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210826_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='plan_complet_date',
            new_name='finished',
        ),
        migrations.RemoveField(
            model_name='task',
            name='plan_complet_date',
        ),
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата окончания'),
        ),
    ]
